### ISSUE TITLE
Up to date ISA documentation

### ISSUE THREAD

**Issue by jrozner** [espressif/llvm-xtensa#11]
Is there up to date public documentation about the instruction set and the encoding of the machine code? I'm interested in building disassembler support into IDA and/or Ghidra and having trouble finding anything short of going into the gcc/llvm port and reading how it's handled there.

**Comment by igrr** [comment]
@jrozner I'm afraid aside from the docs you may find on Google ("Xtensa ISA reference manual") and the source code of the projects such as binutils, QEMU, and LLVM, there isn't anything else. Cadence has not released the ISA reference manual publicly.

Regarding IDA support, https://github.com/pfalcon/ida-xtensa2 may be of interest to you.
