### ISSUE TITLE
Is the long term plan to merge back to upstream LLVM?

### ISSUE THREAD

**Issue by dorfsmay** [espressif/llvm-xtensa#13]
Is the long term plan to merge back to upstream LLVM? Is there any timeline? I am trying to use Rust on the ESP8266 and ESP32 and trying to understand the longterm viability.

Could you add the plan and timeline to the main README?

**Comment by igrr** [comment]
There is an explanation in https://github.com/espressif/llvm-xtensa/issues/8, please follow the link and click the "Subscribe" button to get notified on further updates.

**Comment by dorfsmay** [comment]
Ok, I'll closed this issue then. Would it make sense to mention issue #8 in the README so it is obvious to anybody looking at this project?

Thanks.
