### ISSUE TITLE
Support for ESP32-S2

### ISSUE THREAD

**Issue by lexxvir** [espressif/llvm-xtensa#6]
Hi,

Espressif [announces](https://www.espressif.com/en/news/espressif-announces-%E2%80%A8esp32-s2-secure-wi-fi-mcu) new MCU: ESP32-S2.
Does llvm-xtensa supports ESP32-S2 ?

If no, then is there date when support can be released?

Thanks in advance

**Comment by igrr** [comment]
@lexxvir Support for ESP32-S2 in LLVM is planned around the same time as ESP32-S2 will be supported in ESP-IDF. I can't give a specific date, unfortunately, but it will definitely be no later than the chip enters mass production. Please follow the announcements on the website.

**Comment by lexxvir** [comment]
Thank you @igrr ! We looking forward ESP32-S2 because it is more suitable for our needs (mpos).

**Comment by wis** [comment]
@igrr Hey Ivan, as far as I can infer, ESP32-S2 will enter mass production soon, so the ESP32-S2 will support clang before the ESP32? is that because LX7 unlike LX6 has a _(official)_ LLVM backend from Cadence?

**Comment by igrr** [comment]
The official LLVM backend from Cadence can support ESP32 as well. However it is only available from Cadence under NDA, along with the rest of the Xtensa tools.

Supporting ESP32-S2 in our version of the backend isn't a problem though, as the ESP32-S2 has less CPU features than the ESP32. It should happen before the chip enters mass production.
